# YAML build definition for this app
queue: Hosted Linux Preview
variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: "**/*.csproj"

- task: dotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: "**/*.csproj"
    arguments: --configuration $(buildConfiguration)

- task: dotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test 
    projects: "**/*[Tt]ests/*.csproj"
    arguments: --configuration $(buildConfiguration)

- task: dotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    arguments: --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: true

- task: publishBuildArtifacts@1
  displayName: Publish artifact
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    ArtifactType: Container
